<?

$run_modes = array(
  'development',
  'production',
);

if(!isset($params['build'])) 
{
  $params['build'] =   array (
    'pat'=>'',
    'path' => '',
    'run_mode' => 'development',
    'database' => 
    array (
      'host' => '',
      'username' => '',
      'password' => '',
      'catalog' => '',
    ),
    'http_auth' => 
    array (
      'username' => 'admin',
      'password' => 'admin',
    ),
  );
}
$params['build']['errors'] = array();


if(is_postback())
{
  $pat = $params['build']['pat'];
  unset($params['build']['pat']);
  unset($params['build']['errors']);
  $__click['sites'][$pat] = $params['build'];
  $setup = "\$__click['sites'] = " . s_var_export($__click['sites']);
  $code = <<<CODE
<?
// This file is auto-generated by the Click admin.
$setup
;
CODE;
  file_put_contents(ROOT_FPATH."/sites.php", $code);
  flash_next('Build saved.');
  redirect_to(list_builds_url());
}
