<?

unset($__click['sites'][$params['pat']]);

$setup = "\$__click['sites'] = " . s_var_export($__click['sites']);
$code = <<<CODE
<?
// This file is auto-generated by the Click admin.
$setup
;
CODE;
file_put_contents(ROOT_FPATH."/sites.php", $code);
flash_next('Build deleted');
redirect_to(list_builds_url());
