<?

$run_modes = array(
  'development',
  'production',
);

if(!isset($params['build'])) 
{
  $params['build'] = $__click['sites'][$params['pat']];
  $params['build']['pat'] = $params['pat'];
}
$params['build']['errors'] = array();


if(is_postback())
{
  $pat = $params['build']['pat'];
  unset($params['build']['pat']);
  unset($params['build']['errors']);
  $__click['sites'][$pat] = $params['build'];
  $setup = "\$__click['sites'] = " . s_var_export($__click['sites']);
  $code = <<<CODE
<?
// This file is auto-generated by the Click admin.
$setup
;
CODE;
  file_put_contents(ROOT_FPATH."/sites.php", $code);
  flash_next('Build saved.');
  redirect_to(list_builds_url());
}
