<?
// This file is auto-generated by the Click admin.
$__click['sites'] = array (
  '*' => 
  array (
    'path' => 'rootkit',
    'run_mode' => 'development',
    'database' => 
    array (
      'host' => '',
      'username' => '',
      'password' => '',
      'catalog' => '',
    ),
    'http_auth' => 
    array (
      'username' => 'admin',
      'password' => 'admin',
    ),
  ),
)
;