<?
// This file is auto-generated by the Click admin.
$__click['sites'] = array (
  '*' => 
  array (
    'path' => 'rootkit',
    'run_mode' => 'development',
    'database' => 
    array (
        'host' => '',
        'username' => '',
        'password' => '',
        'catalog' => '',
    ),
    'http_auth' => 
    array (
      'username' => 'admin',
      'password' => 'admin',
    ),
  ),
  'avsms' => 
  array (
    'path' => 'avsms',
    'run_mode' => 'development',
    'database' => array(
        'host' => '172.19.1.56',
        'username' => 'root',
        'password' => 'r00t',
        'catalog' => 'avsms',
    ),
    'http_auth' => 
    array (
      'username' => '',
      'password' => '',
    ),
  ),  
)
;